# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-14 15:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_bids', models.IntegerField()),
                ('time_starting', models.DateTimeField()),
                ('time_ending', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Auctions',
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_time', models.DateTimeField()),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.Auction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Bids',
            },
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('origin', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('age', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('category', models.CharField(choices=[('NUL', 'Select a category'), ('MIL', 'Military'), ('RLE', 'Real Estate'), ('WEA', 'Weapons'), ('CUL', 'Cultural')], max_length=3)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'lot items',
            },
        ),
        migrations.AddField(
            model_name='auction',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.Lot'),
        ),
    ]
