# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-14 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='buy_now',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='auction',
            name='number_of_bids',
            field=models.IntegerField(default=0),
        ),
    ]
