# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-14 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_auto_20191214_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
