# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-16 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_bid_bid_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='description',
            field=models.TextField(default='Newage Auctions'),
        ),
    ]
