# Generated by Django 3.0 on 2019-12-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_auction_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
