# Generated by Django 3.0 on 2019-12-30 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0006_auction_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
