# Generated by Django 3.0 on 2020-01-01 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0009_lot_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='buy_now',
        ),
    ]
