# Generated by Django 3.0 on 2020-01-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0010_remove_auction_buy_now'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='category',
            field=models.CharField(choices=[('NUL', 'Select a category'), ('Military', 'Military'), ('Real Estate', 'Real Estate'), ('Weapons', 'Weapons'), ('Cultural', 'Cultural')], max_length=11),
        ),
    ]
