# Generated by Django 3.0 on 2020-01-02 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0011_auto_20200101_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='category',
            field=models.CharField(choices=[('NUL', 'Select a category'), ('military', 'Military'), ('real estate', 'Real Estate'), ('weapons', 'Weapons'), ('cultural', 'Cultural')], max_length=11),
        ),
    ]
