# Generated by Django 3.0 on 2020-01-11 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0012_auto_20200102_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='lot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auction.Lot'),
        ),
    ]
