# Generated by Django 3.0 on 2019-12-28 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20191228_1521'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
